adapters: 
  - http
  - ws
debug: false
enableVerify: true
verifyKey: INITKEYLaI8BnP9
singleMode: false
cacheSize: 4096
## adapter 的单独配置，键名与 adapters 项配置相同
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: localhost
    port: 8080
    cors: ["*"]
  
  ## 详情看 websocket adapter 使用说明 配置
  ws:
    host: localhost
    port: 8080
    reservedSyncId: -1